### ISSUE TITLE
How to connect with HTC Vive

### ISSUE THREAD

**Issue by umairarif88** [phananh1010/PanoSaliency#1]
Hi, thanks for sharing the code. I was reading your paper and you mentioned in the paper this software can get data from any hardware. can i use this software to track head gaze from HTC VIVE ?
thank you. 
umairarif88@gmail.com

**Comment by phananh1010** [comment]
Hello, the software is used to generate saliency maps from head movement. To actually track head gaze, you need to use the API provided for HTC VIVE.

Anh
