### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by EricPengShuai** [phananh1010/PanoSaliency#2]
1. In the [dataset](https://zenodo.org/record/2641282#.YGA5BGQza3J) you provided, I found that for the 5th and 6th videos of the second data set, the saliency map is divided into several small parts. Was it extracted separately because the data was too large?
![dataset](https://i.loli.net/2021/03/29/97yMwOWEvNIftbR.png)

2. You mentioned the format of the saliency dataset in your [README](https://github.com/phananh1010/PanoSaliency#360-degree-saliency-dataset): the first field is a timestamp, the second field is a list of fixation points, and the third field is a saliency map. I want to know how to visualize fixation map and saliency map like in your paper. Thanks a lot!

**Comment by phananh1010** [comment]
Hello,

1. Yes, because the videos were too long, they were split. 
2. The  third columns contain 2D heat map, which can be show using any visualization tools. The second column is a list of coordinates (x, y) of the fixations points. It is sufficient to plot them in any tools.
