### ISSUE TITLE
How did you draw the gazing points on the image?

### ISSUE THREAD

**Issue by aiguo112** [phananh1010/PanoSaliency#3]
Hi, i know this question is not related to the code or dataset. But its more related to the paper results. 

Can you please tell me how to re-generate these results on image? 
![Screenshot_4](https://user-images.githubusercontent.com/81693706/123728585-10170380-d8c6-11eb-986f-9efad33cfb9a.png)

**Comment by phananh1010** [comment]
I used the scatter function in the matplotlib tool. https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html

**Comment by aiguo112** [comment]
Love you bro, you saved my ass.
