### ISSUE TITLE
question about H and W 

### ISSUE THREAD

**Issue by sousoul** [phananh1010/PanoSaliency#4]
Hi, I am confused with the variable `H` and `W` in `head_orientation_lib.py`,  in this file, `H` is initialized to be 90 and `W` is initialized to be 160; In the paper these two variables seem to refer to the width and height of the target equirectangular frame. 

> W and H are the width and height of the target equirectangular frame.

so my question is why these two variables are set to be 90 and 160.

**Comment by sousoul** [comment]
I print the results by uncommenting the code from line 155 to line 159 in parima.py，
```
		######################################################
		# print("x: "+str(x_act))
		# print("x_pred: "+str(x_pred))
		# print("y: "+str(y_act))	
		# print("y_pred: "+str(y_pred))
		# print("("+str(actual_tile_row)+","+str(actual_tile_col)+"),("+str(pred_tile_row)+","+str(pred_tile_col)+")")
		# # ######################################################
```
and find that the prediction is always located in (0, 0) (1, 0) (1, 1)tiles , the results are like belows:
```
x: 161
x_pred: 625.5722775570365
y: 155
y_pred: 306.84832202756934
(0,0),(1,1)
x: 161
x_pred: 625.6430497567117
y: 155
y_pred: 306.7216460505056
(0,0),(1,1)
x: 170
x_pred: 625.9193381905325
y: 158
y_pred: 306.90741257262346
(0,0),(1,1)
x: 178
x_pred: 625.8357150417579
y: 160
y_pred: 306.7751003190363
(0,0),(1,1)
x: 178
x_pred: 625.7140908126182
y: 160
y_pred: 306.78683072215523
(0,0),(1,1)
```

**Comment by phananh1010** [comment]
Hello,

The value of H and W are arbitrarily set. You can change these number to output the map of a different size.

About the code section. I am not sure what is it doing. In my repository there is no file named parima.py
