### ISSUE TITLE
About the second field in your dataset

### ISSUE THREAD

**Issue by EricPengShuai** [phananh1010/PanoSaliency#5]
Hello, I would like to ask about the second field in every record of your dataset. For example, in the **saliency_ds2_topic0**, each record has three fields: timestamp, fixation, and saliency maps. You mentioned that the second field (fixation) is a list of fixation points in your paper.

But I found that the length of the fixation list corresponding to different timestamps is different? It stands to reason that the length of the list should be 48, representing the viewing points of 48 users. Are these fixation lists obtained by deleting some isolated fixation points?

---
In addition, why do you flip the fixation matrix from left to right and then from top to bottom when you calculate the fixation map in **dataset2** (_np.fliplr, np.flipud_).
https://github.com/phananh1010/PanoSaliency/blob/b0749694264bb9203c46768036d1a4f1319305b6/saldat_head_orientation.py#L291
```python
def create_fixation_map(self, fixation_list, dataset):
    result = np.zeros(shape=(head_orientation_lib.H, head_orientation_lib.W), dtype=np.int)
    pixel_list = self.create_fixation_pixellist(fixation_list)
    for x, y in pixel_list:
        result[int(x), int(y)] = 1
    
    if dataset == self._DATASET2:
        result1 = np.fliplr(result)
        result1 = np.flipud(result1)
```

**Comment by phananh1010** [comment]
Hello, the fixation points describe the location where users stop moving and look at. In this case, users who are moving their head will not have fixations.
We use a coordination system different from other authors, so the flipping is the adjustment to map our fixations location to the coordinate system established by different datasets.
